# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('dim_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
    ]
