# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='act_date',
            field=models.DateTimeField(null=True, verbose_name='活动结束时间'),
        ),
    ]
