# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adv_act_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='language',
            field=models.CharField(default='en', max_length=500, verbose_name='内容'),
        ),
    ]
